apiVersion: apps/v1
kind: Deployment
metadata:
  name: resource-container
spec: 
  selector:
    matchLabels:
      app: resource-container
  template:
    metadata:
      labels:
        app: resource-container
    spec: 
      containers:
      - name: resource-container
        image: gcr.io/kubernetes-e2e-test-images/resource-consumer:1.5
        livenessProbe:
          httpGet:  ## Opções: httpGet, tcpSocker, Exec
            path: /health
            port: 8080
            scheme: HTTP
        readnessProbe:
          httpGet:  ## Opções: httpGet, tcpSocker, Exec
            path: /ready
            port: 8080
            scheme: HTTP
        startupProbe:
          httpGet:  ## Opções: httpGet, tcpSocker, Exec
            path: /health
            port: 8080
            scheme: HTTP            
        resources: 
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "32Mi"
            cpu: "100m"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata: 
  name: resource-container-service
spec: 
  selector:
    app: resource-container
  ports:
  - port: 80
    targetPort: 8080
  type: LoadBalancer