namespace: infraestrutura
imagem: registry.xpto/nginx:v1.0
targetport: 80
replicas: 2
memory: 100Mi
cpu: 0.5
volume:
  name: 
  path: /var/www/html
  tamanho: 100Mi
ingress:
  host: app.domain.xpto
  path: /sistema
  tls: cert-ssl
vars:
 chave1: valor1
 chave2: valor2
 chave3: valor3
secrets:
 chave1: valor1
 chave2: valor2
 chave3: valor3