apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ aplicacao }}-pvc
  namespace: {{ namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-client
  resources:
    requests:
      storage: 100Mi
