apiVersion: v1
kind: Service
metadata:
  name: {{ aplicacao }}-service
  namespace: {{ namespace }}
spec:
  selector:
    app: {{ aplicacao }}
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP