apiVersion: apps/v1
kind: Deployment
metadata:
  name: bdcadastros-deployment
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels: 
        app: mysql
    spec:
      containers:
        - name: bdcadastros
          image: julianorib/bdcadastros:v1.0
          ports:
            - containerPort: 3306
#          volumeMounts:
#            - name: bdcadastros-data
#              mountPath: /var/lib/mysql/data
#      volumes:
#        - name: bdcadastros-data
#          PersistentVolumeClaim: 
#            claimName: bdcadastros-pvc