apiVersion: apps/v1
kind: Deployment
metadata: 
  name: {{ .Release.Name }}-nginxdeploy
spec: 
  replicas: 4
  selector: 
    matchLabels:
      app: {{ .Release.Name }}-nginx
  template:
    metadata:
      labels: 
        app: {{ .Release.Name }}-nginx
    spec: 
      containers:
        - name: {{ .Release.Name }}-nginx
          image: nginx:{{ .Values.nginx.version }}
          livenessProbe:
            httpGet:
              path: /
              port: 80
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 2
            periodSeconds: 2
