apiVersion: apps/v1
kind: Deployment
metadata: 
  name: teste-deploy
spec: 
  replicas: 4
  selector: 
    matchLabels:
      app: teste
  template:
    metadata:
      labels: 
        app: teste
    spec: 
      containers:
        - name: teste
          image: julianorib/teste:v1.1
          livenessProbe:
            httpGet:
              path: /
              port: 80
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 2
            periodSeconds: 2
---
apiVersion: v1
kind: Service
metadata:
  name: teste-service
spec:
  selector:
    app: teste
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer
